import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../globals.css";

import { Locale } from "@/i18n.config";
import { Link } from "lucide-react";
import Dashboard from "../(protected)/dashboard/page";
const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link href="/dashboard" className="flex items-center gap-2 flex-grow">
          <span>Dashboard</span>
        </Link>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
